BUILDSCAD_PROJECT=dfCharacterBuilder
BUILDSCAD_VERSION=1.0.0
BUILDSCAD_AUTHOR=me
BUILDSCAD_ASSEMBLIES=scad/main.scad
# BUILDSCAD_LOG_LEVEL=INFO
# BUILDSCAD_OPENSCAD_PATH=/usr/bin/openscad
# BUILDSCAD_OUTPUT_FORMAT=stl
# BUILDSCAD_OPENSCAD_COLORSCHEME=Cornfield
# BUILDSCAD_IMAGESIZE=1280,720
# BUILDSCAD_THREADS=1
# BUILDSCAD_ENABLE_EXPERIMENTAL=false
